server:
  port: 8099

spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true