spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oauth
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create


# JPA Query Parameter Value
logging:
  level:
    org.hibernate.type: trace
